name: Build and Deploy Pandemic Survey Stack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-frontend-image:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 6

    - name: Build frontend image
      run: |
        docker build . \
          --file ./Dockerfile \
          --tag ghcr.io/ou-disc/pandemic-survey:$SHA
      env:
          SHA: ${{ steps.short-sha.outputs.sha }}

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Push images
      run: |
        docker push ghcr.io/ou-disc/pandemic-survey:$SHA
      env:
          SHA: ${{ steps.short-sha.outputs.sha }}


  deployment:
    needs:
      - build-frontend-image
    runs-on: 'ubuntu-latest'
    timeout-minutes: 40
    steps:
    - uses: actions/checkout@v4

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 6

    ################################################################################################################
    #
    # The deploy job requires a kubeconfig. To use that, take the kubeconfig file from
    # ~/.kube/config and edit the IP address in there to:
    # server: https://disc.ourcloud.ou.edu:6443
    #
    # Then copy the file contents and add it to the project -> settings -> variables -> actions
    # Name the variable KUBECONFIG and paste the contents as the value.
    #
    ################################################################################################################
    - name: WriteKubeConfig
      run: |
        mkdir -p ~/.kube
        echo "$KUBECONFIG_CONTENT" > ~/.kube/config
      env:
        KUBECONFIG_CONTENT: '${{ secrets.KUBECONFIG }}'

    - uses: helmfile/helmfile-action@v2.4.0
      with:
        helm-plugins: >
          https://github.com/databus23/helm-diff,
          https://github.com/jkroepke/helm-secrets
        helmfile-args: --debug apply
      env:
        SHA: ${{ steps.short-sha.outputs.sha }}

    - name: Debug cluster state on failure
      if: failure()
      run: |
        kubectl -n basheer get pods -o wide || true
        kubectl -n basheer get deploy || true
        kubectl -n basheer get events --sort-by=.lastTimestamp | tail -n 200 || true